apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: church-dashboard-treafik-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: church-dashboard-treafik
    k8s.kuboard.cn/workload: church-dashboard-treafik
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd

spec:
  tls:
    - hosts:
        - dashboard.xpool.top
      secretName: xpool-top-tls
  rules:
    - host: dashboard.xpool.top
      http:
        paths:
          - path: /
            backend:
              serviceName: church-dashbaord
              servicePort: 80
